repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: check-toml
      - id: check-yaml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Flake8

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        name: PyDocsStyle
        exclude: tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        name: Mypy
        language: system
        exclude: tests/

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2
    hooks:
      - id: pylint
        name: pylint
        args:
          - django-settings-module=fishka_backend.settings
        language: system
        exclude: tests/
