# Generated by Django 3.1.2 on 2020-10-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=20, unique=True)),
                ('category_type', models.CharField(choices=[('framework', 'Framework'), ('team', 'Team'), ('language', 'Language')], editable=False, help_text='Category type', max_length=9)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.category')),
            ],
            bases=('categories.category',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.category')),
            ],
            bases=('categories.category',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.category')),
            ],
            bases=('categories.category',),
        ),
    ]
