# Generated by Django 3.1.7 on 2021-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('framework', 'Framework'), ('team', 'Team'), ('language', 'Language')], editable=False, help_text='Category type', max_length=9, verbose_name='Category type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name', max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
