# Generated by Django 3.1.2 on 2020-10-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question title', max_length=100, unique=True)),
                ('answer', models.TextField(help_text='Question answer', max_length=500)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], db_index=True, help_text='Difficulty level of question', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(db_index=True, help_text='Question categories', to='categories.Category')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
