# Generated by Django 3.1.2 on 2020-10-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question title', max_length=100, unique=True)),
                ('answer', models.TextField(help_text='Question answer', max_length=500)),
                ('difficulty', models.CharField(choices=[('e', 'Easy'), ('i', 'Intermediate'), ('h', 'Hard')], db_index=True, help_text='Difficulty level of question', max_length=1)),
                ('is_public', models.BooleanField(default=True, help_text='Field specifies if user can see question instance')),
                ('author_email', models.EmailField(blank=True, default=None, help_text='Email address of question author', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(blank=True, default=None, help_text='Question framework category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.framework')),
                ('language', models.ForeignKey(blank=True, default=None, help_text='Question language category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.language')),
                ('team', models.ForeignKey(blank=True, default=None, help_text='Question team category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSuggestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('questions.question',),
        ),
    ]
