# Generated by Django 3.1.2 on 2020-10-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='framework',
            field=models.ForeignKey(blank=True, default=None, help_text='Question framework category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.framework'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, default=None, help_text='Question language category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team',
            field=models.ForeignKey(blank=True, default=None, help_text='Question team category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.team'),
        ),
    ]
