# Generated by Django 3.1.7 on 2021-03-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210306_1042'),
        ('questions', '0002_auto_20201031_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(help_text='Question answer', max_length=500, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_email',
            field=models.EmailField(blank=True, default=None, help_text='Email address of question author', max_length=254, null=True, verbose_name='Author email'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when an object was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('e', 'Easy'), ('i', 'Intermediate'), ('h', 'Hard')], db_index=True, help_text='Difficulty level of question', max_length=1, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='framework',
            field=models.ForeignKey(blank=True, default=None, help_text='Question framework category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.framework', verbose_name='Framework category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Field specifies if user can see question instance', verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, default=None, help_text='Question language category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.language', verbose_name='Language category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='Question title', max_length=100, unique=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team',
            field=models.ForeignKey(blank=True, default=None, help_text='Question team category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.team', verbose_name='Team category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when an object was last updated', verbose_name='Updated at'),
        ),
    ]
